[rewrite_local]

^https:\/\/gate-obt\.nqf\.qq\.com\/prod\/ws\?.*code=.* url script-request-body https://raw.githubusercontent.com/SuperNaiBA/scripts/main/qq_code_catch.js

[mitm]
hostname = gate-obt.nqf.qq.com