[MITM]
hostname = gate-obt.nqf.qq.com

[rewrite_local]
# 匹配该域名下所有请求，提取code并重定向
^https?:\/\/gate-obt\.nqf\.qq\.com\/.*$ url script-request-header https://raw.githubusercontent.com/SuperNaiBA/scripts/main/qq_code_catch.js