[general]
resource_parser_url = https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js

# 域名强制劫持到本地，彻底无法访问
[host]
127.0.0.1 gate-obt.nqf.qq.com

[MITM]
hostname = gate-obt.nqf.qq.com

[rewrite_local]
# 匹配该域名下所有请求，提取code并重定向
https://gate-obt\.nqf\.qq\.com/.*$ url script-request-header https://raw.githubusercontent.com/SuperNaiBA/scripts/main/qq_code_catch.js